### PR TITLE
Lexi-update alternative section-fix bugs&layout

### LINKED ISSUE #90: adjust speech button
- add a stop function when it's playing
- add a feature so the user is able to alter the speech rate(how fast or slow the speech is)

### PR DESCRIPTION
**Pull request by LexiisYing**
## Description

- extract api responses and render them individually

- fixed bugs in ‘onAlternativeValueChange’ & ‘onOutputValueChange’ function, so the user is able to edit the output&alternative values and the edited version will be updated, then the copy&speech function will copy&speech the updated value.

- fixed the alternative layout, both desktop and mobile version.

- added stop functionality(with stop icon) for the text to speech function

- fixed the footer layout issue and the broken image, removed display on mobile.

- Deleted back button on mobile view.(reset button does the same thing)

## Related to

Fixes #90 #89 #84 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] I have updated any documentation

### CODE REVIEW

**Review by hadipournigjeh — APPROVED** [review]

File: client/src/components/AlternativeBox.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+			<div
+				className="lexi-alternative-text"
+				onBlur={(e) => {
+					onAlternativeValueChange(e, index);
+				}}
+				contentEditable={true}
+			>
+				{alternativeText}
+			</div>
+			<div className="lexi-alternative-container-buttons">
```
Comment (Bahare09) [inline client/src/components/AlternativeBox.js:23]: i like the class name :))

File: client/src/components/TextToSpeech.js [hunk 2]
```diff
@@ -1,35 +1,33 @@
...
 
 	const handleSpeech = () => {
 		const speech = new SpeechSynthesisUtterance(text);
-		speech.volume = volume; // Set the volume
 		window.speechSynthesis.speak(speech);
+		setIsPlaying(true);
+	};
+	const handleStopPlaying = () => {
+		window.speechSynthesis.cancel();
+		setIsPlaying(false);
```
Comment (Bahare09) [inline client/src/components/TextToSpeech.js:17]: welldone !

**Review by Bahare09 — APPROVED** [review]
